// Decompiled by Jad v1.5.8e2. Copyright 2001 Pavel Kouznetsov.
// Jad home page: http://kpdus.tripod.com/jad.html
// Decompiler options: packimports(3) 
// Source File Name:   MapperConfigPlugin.java

package org.mybatis.generator.plugins;

import java.util.*;
import org.mybatis.generator.api.*;
import org.mybatis.generator.api.dom.xml.*;
import org.mybatis.generator.internal.util.StringUtility;
import org.mybatis.generator.internal.util.messages.Messages;

public class MapperConfigPlugin extends PluginAdapter
{

    public MapperConfigPlugin()
    {
        mapperFiles = new ArrayList();
    }

    public boolean validate(List warnings)
    {
        boolean valid = true;
        if(!StringUtility.stringHasValue(properties.getProperty("targetProject")))
        {
            warnings.add(Messages.getString("ValidationError.18", "MapperConfigPlugin", "targetProject"));
            valid = false;
        }
        if(!StringUtility.stringHasValue(properties.getProperty("targetPackage")))
        {
            warnings.add(Messages.getString("ValidationError.18", "MapperConfigPlugin", "targetPackage"));
            valid = false;
        }
        return valid;
    }

    public List contextGenerateAdditionalXmlFiles()
    {
        Document document = new Document("-//mybatis.org//DTD Config 3.0//EN", "http://mybatis.org/dtd/mybatis-3-config.dtd");
        XmlElement root = new XmlElement("configuration");
        document.setRootElement(root);
        root.addElement(new TextElement("<!--"));
        root.addElement(new TextElement("  This file is generated by MyBatis Generator."));
        root.addElement(new TextElement("  This file is the shell of a Mapper Config file - in many cases you will need to add"));
        root.addElement(new TextElement("    to this file before it is usable by iBATIS."));
        StringBuilder sb = new StringBuilder();
        sb.append("  This file was generated on ");
        sb.append(new Date());
        sb.append('.');
        root.addElement(new TextElement(sb.toString()));
        root.addElement(new TextElement("-->"));
        XmlElement mappers = new XmlElement("mappers");
        root.addElement(mappers);
        XmlElement mapper;
        for(Iterator iterator = mapperFiles.iterator(); iterator.hasNext(); mappers.addElement(mapper))
        {
            String mapperFile = (String)iterator.next();
            mapper = new XmlElement("mapper");
            mapper.addAttribute(new Attribute("resource", mapperFile));
        }

        GeneratedXmlFile gxf = new GeneratedXmlFile(document, properties.getProperty("fileName", "MapperConfig.xml"), properties.getProperty("targetPackage"), properties.getProperty("targetProject"), false);
        List answer = new ArrayList(1);
        answer.add(gxf);
        return answer;
    }

    public boolean sqlMapGenerated(GeneratedXmlFile sqlMap, IntrospectedTable introspectedTable)
    {
        StringBuilder sb = new StringBuilder();
        sb.append(sqlMap.getTargetPackage());
        sb.append('.');
        String temp = sb.toString();
        sb.setLength(0);
        sb.append(temp.replace('.', '/'));
        sb.append(sqlMap.getFileName());
        mapperFiles.add(sb.toString());
        return true;
    }

    private List mapperFiles;
}
